# conda env create -f environment.yml && conda activate DFP
name: DFP
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.23
  - matplotlib>=3.7
  - casadi>=3.6
  - scipy            # optional (development convenience)
  - streamlit        # optional (dashboard only)
  - pytest
  - pip
