[project]
name = "diafiltration"
version = "0.1.0"
description = "Batch diafiltration model + time-optimal MPC (APC 2025)"
authors = [{name="Your Name", email="you@example.com"}]
dependencies = [
    "casadi>=3.6.2",
    "numpy",
    "matplotlib"
]

[project.optional-dependencies]
dev = ["pytest"]
