name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Miniconda (Python 3.9)
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml           # ← ваш файл с Python 3.9
          activate-environment: diafiltration_mpc_SS25
          auto-activate-base: false

      - name: Install package in editable mode
        shell: bash -l {0}
        run: |
          python -m pip install --quiet -e .[dev]

      - name: Run test suite
        shell: bash -l {0}
        run: |
          pytest -q
